project_id = "ixrfzvzffvrslakqqwxa"

[functions.analyze-food]
verify_jwt = true

[functions.analyze-medical-document]
verify_jwt = true

[functions.analyze-vitals]
verify_jwt = true

[functions.health-chatbot]
verify_jwt = true

[functions.generate-diet-plan]
verify_jwt = true

[functions.analyze-nutrition]
verify_jwt = true

[functions.search-doctors]
verify_jwt = true

[functions.nutrition-chatbot]
verify_jwt = true

[functions.search-foods]
verify_jwt = true
